name: WarpButtons
main: me.chaseoes.warpbuttons.WarpButtons
version: 1.0
description: Create buttons that are linked to warps.
commands:
  warpbuttons:
    description: The central command for the WarpButtons plugin.
    usage: /<command> [args]
    aliases: [wb]